version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: orthancteam/orthanc:latest-full
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - ./orthanc.json:/run/secrets/orthanc.json:ro
      - ./orthanc-db:/var/lib/orthanc/db
    environment:
      - ORTHANC_NAME=MyOrthanc
secrets:
  orthanc.json:
    file: orthanc.json
